# Generated by Django 3.2.5 on 2021-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_billspayments_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_expense',
            field=models.IntegerField(null=True),
        ),
    ]
