# Generated by Django 3.2.5 on 2021-08-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_billspayments_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='bill',
        ),
    ]
