# Generated by Django 3.2.5 on 2021-08-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_transactions_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.billspayments'),
        ),
    ]
