# Generated by Django 3.2.5 on 2021-08-08 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210808_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_expense',
            new_name='extra_income',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='paycheck_income',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billspayments',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('insurance', 'Insurance'), ('food', 'Food'), ('savings', 'Savings'), ('transportation', 'Transportation'), ('giving', 'Giving'), ('personal', 'Personal'), ('utilities', 'Utilities'), ('medical', 'Medical'), ('clothing', 'Clothing'), ('others', 'Others')], default='Choose a category', max_length=50),
        ),
    ]
