# Generated by Django 3.2.5 on 2021-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210808_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(default='8-2021', max_length=10),
        ),
    ]
