# Generated by Django 3.2.5 on 2021-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210808_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(default='8-2021', max_length=10, unique=True),
        ),
    ]
