# Generated by Django 3.2.5 on 2021-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(default='8-2021', error_messages={'unique': "You've already set the budget for this month."}, max_length=10, unique=True),
        ),
    ]
