# Generated by Django 3.2.5 on 2021-08-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_budget_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billspayments',
            name='month',
        ),
    ]
