# Generated by Django 3.2.5 on 2021-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_billspayments_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billspayments',
            name='status',
        ),
        migrations.AddField(
            model_name='billspayments',
            name='expense_date',
            field=models.DateField(null=True),
        ),
    ]
