# Generated by Django 3.2.5 on 2021-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='symbol',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
