# Generated by Django 3.2.5 on 2021-08-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_wallet_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
